# Generated by Django 5.0 on 2024-01-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('item', '0004_alter_item_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
